### ISSUE TITLE
Reconsider how IDAS is integrated

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-devguide-app#103]
Integration between IDAS and Orion should be done without relying on any kind of notification mechanism. Actually, IDAS allows to map incoming readings from devices to entities in a Context Broker. So current approach seems to be unnecessary.

**Comment by dmabtrg** [comment]
I'll look into it.  Do you have any pointers to the documentation on how to do this?

**Comment by jmcanterafonseca** [comment]
you will see it soon in the Tour Guide documentation under http://fiwaretourguide.readthedocs.io/en/latest/connection-to-the-internet-of-things/how-to-read-measures-captured-from-iot-devices/

**Comment by dmabtrg** [comment]
Fixed in #110.
