### ISSUE TITLE
change attribute type `date` to `DateTime` to align with Orion Context Broker

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-devguide-app#114]
with the recent change of Orion Context Broker from `date`to `DateTime`we need to align

this change also affects the Cookbook and the client app

/cc @FiwareULPGC

**Comment by albertinisg** [comment]
Resources were already aligned in #115 and https://github.com/telefonicaid/fiware-orion/issues/2273 , so I'm closing the issue.
