### ISSUE TITLE
Map view displays a limited amount of restaurants

### ISSUE THREAD

**Issue by dmabtrg** [Bitergia/fiware-devguide-app#2]
While testing the map, I can only see restaurant POIs for about 40~50 restaurants.  I've checked [client/js/restaurants_api.js](https://github.com/Bitergia/fiware-devguide-app/blob/74da7b8d9478ed56a77367d8a851a7dddefcaa58/client/js/restaurants_api.js#L59-L68) and there seems to be a variable clash between the len variable in the first for loop and that same variable in the inner for loop.  Using different variable names seems to fix this and shows all the restaurant POIs.

**Comment by FiwareULPGC** [comment]
Fixed in 67e87f32954c4a897de6a70066a8df7d3ad0cc22
