### ISSUE TITLE
use the latest Orion Context Broker docker image

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-devguide-app#42]

**Comment by albertinisg** [comment]
@dmabtrg to update Orion => 0.28 I will have to replace all the id's whitespaces for 'underscore'. Take note of this action, as it probably may change the behavior of the sensors in IDAS GE.

**Comment by albertinisg** [comment]
@jmcanterafonseca Orion 0.28 is the latest version that supports XML. CEP does not support the Orion JSON format for notifications (as discussed [here](https://github.com/ishkin/Proton/issues/15#issuecomment-173275454)), so I'm afraid that we will have to stop the update process at version 0.28 until a decision is made.

**Comment by jmcanterafonseca** [comment]
I would suggest the following:

use always the _latest_ Orion Context Broker version

provide an alternative target in docker-compose (or a different compose
file) to work with CEP.

But I would not lose all the Orion nice features that are going to land
just because CEP is not updated.

thanks

2016-03-16 15:20 GMT+01:00 Alberto Martín notifications@github.com:

**Comment by albertinisg** [comment]
Done in #59
