### ISSUE TITLE
Create a readthedocs documentation project for the application

### ISSUE THREAD

**Issue by jmcanterafonseca** [Bitergia/fiware-devguide-app#49]

**Comment by albertinisg** [comment]
Task on hold
https://github.com/Fiware/tutorials.TourGuide-App/pull/70#issuecomment-223984451

**Comment by albertinisg** [comment]
The readthedocs documentation was finally added in https://github.com/Fiware/docs.TourGuide/.
See http://fiwaretourguide.readthedocs.io/en/latest/fiware-tour-guide-application-a-tutorial-on-how-to-integrate-the-main-fiware-ges/introduction/#introduction
