### ISSUE TITLE
Migrate to an Open Geocoder

### ISSUE THREAD

**Issue by albertinisg** [Bitergia/fiware-devguide-app#63]
Actually we are using Google's API to Geocode the restaurants. We should migrate to an Opensource geocoder provider.

**Comment by albertinisg** [comment]
After having a look at several providers, I think a good choice could be [Opencagedata](https://geocoder.opencagedata.com/). It's open under ODbL and CC-BY-SA licenses: https://geocoder.opencagedata.com/faq#legal and also supported by the node-module we are using (node-geocoder). The only thing is, every user will need to use an `apiKey`, which will be passed as an argument when running the feeder.

**Comment by albertinisg** [comment]
I've been testing several geocoding providers and here are the results:

The open Source ones:
- Openstreetmaps: Searching 5 different address, it could geo-locate just one of them, leaving the others empty.
- datasciencetoolkit: It couldn't find any of the 5 addresses given
- opencage: it does geolocate the entity, but not the streets. It means, returns the geo-location of the city, far from being accurate (and requires `apiKey`)

There were more geocoders like openmapquest or nominatimmapquest, but they use the same geocoder as openstreetmaps and this one didn't work at all.

The non open Source ones:
- Google: it does geolocate 5 of the 5 tested addresses. 
- agol: it does also geolocate the 5 restaurants (but requires `client_id` and `client_secret`)

@jmcanterafonseca the only opensource geocoder that seems to 'work' is opencage, but we will lose accuracy in the geolocation. Should we migrate to that one?

**Comment by jmcanterafonseca** [comment]
do we have other alternatives non open source but without restriction in
the number of requests?

2016-04-04 16:25 GMT+02:00 Alberto Martín notifications@github.com:

**Comment by albertinisg** [comment]
After searching and testing I could't find any other free service (even not opensource) that does offer quality geolocation without any request limitation. There are several opensource ones that offers that, but they are based in openstreetmaps, which did not geolocate very well.
We still can do the following:
- Generate the geolocation data of each restaurant in a file inside the repository (same as the restaurants) so everytime the user wants to feed the image we don't have to request the geolocation everytime.
- Separate the geocoding into another script, that receives the `restaurants.json` file with the original format, and generates a new file with the updated geocoding data (and updating the documentation letting the user know the requests limit).
  Could this be a better approach?

**Comment by albertinisg** [comment]
@jmcanterafonseca how should I proceed with this?

**Comment by albertinisg** [comment]
Approach https://github.com/Fiware/tutorials.TourGuide-App/issues/63#issuecomment-205840078 done in #122
