### ISSUE TITLE
Idas image fails while checking Orion is alive

### ISSUE THREAD

**Issue by albertinisg** [Bitergia/fiware-devguide-app#89]
Bitergia IDAS image checks for the expression `<version>` to check Orion is alive, but since Orion is not using XML anymore, this check fails. The official IDAS image does not check that, so this error should not appear using the official one.

**Comment by jmcanterafonseca** [comment]
please remove any kind of checking that other services are alive. That's something should be done by the original service and it is not our business. Removing any kind of magic behind dockers would help us a lot. this is not a production application it is a tutorial!

**Comment by dmabtrg** [comment]
I'm testing the new [iotagent-ul](https://github.com/telefonicaid/iotagent-ul) in order to replace our custom image with the new official one.

**Comment by dmabtrg** [comment]
Now we are using the official iotagent-ul image, so this can be closed.
